---

- name: Hostname - Get current ComputerName
  shell: scutil --get ComputerName
  register: computername_result
  changed_when: false
  check_mode: no
  when: system.hostname.computername != None

- name: Hostname - Update ComputerName
  shell: scutil --set ComputerName {{ hostname_computername }}
  become: true
  when: system.hostname.computername != None and (system.hostname.computername not in computername_result.stdout)

- name: Hostname - Get current HostName
  shell: scutil --get HostName
  register: hostname_result
  changed_when: false
  failed_when: false
  check_mode: no
  when: system.hostname.hostname != None

- name: Hostname - Update HostName
  shell: scutil --set HostName {{ system.hostname.hostname }}
  become: true
  when: system.hostname.hostname != None and (hostname_result.failed or (system.hostname.hostname not in hostname_result.stdout))

- name: Hostname - Get current LocalHostName
  shell: scutil --get LocalHostName
  register: localhostname_result
  changed_when: false
  check_mode: no
  when: system.hostname.localhostname != None

- name: Hostname - Update LocalHostName
  shell: scutil --set LocalHostName {{ system.hostname.localhostname }}
  become: true
  when: system.hostname.localhostname != None and (system.hostname.localhostname not in localhostname_result.stdout)

